############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 4

[[main]]
name = "Services"
url = "/#services"
weight = 2

[[main]]
name = "Portfolio"
url = "/projects"
weight = 3

##  [[main]]
##  name = "Elements"
##  url = "elements/"
##  weight = 3

[[main]]
weight = 5
name = "Blog"
hasChildren = true


[[main]]
weight = 6
name = "Contact"
url = "contact/"


[[main]]
parent = "Blog"
name = "Articles"
url = "blog/"



##  [[main]]
##  parent = "Pages"
##  name = "Blog"
##  url = "blog/"



[[main]]
parent = "Blog"
name = "Authors"
url = "authors/"

[[main]]
parent = "Blog"
name = "Categories"
url = "categories/"

[[main]]
parent = "Blog"
name = "Tags"
url = "tags/"



## [[main]]
## name = "Elements"
## url = "elements/"
## weight = 6


##  [[main]]
##  parent = "Blog"
##  name = "404 Page"
##  url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 5


[[footer]]
name = "Services"
url = "/#services"
weight = 2

[[footer]]
name = "Projects"
url = "/projects"
weight = 3

[[footer]]
name = "My Unique Value Proposition"
url = "/uvp"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 6

[[footer]]
name = "Terms of Use"
url = "terms-of-use/"
weight = 7

## [[footer]]
## name = "Sitemap"
## url = "sitemap.xml"
#weight = 6

## [[footer]]
## name = "RSS"
## url = "index.xml"
## weight = 7

