############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

##  [[main]]
##  name = "Elements"
##  url = "elements/"
##  weight = 3

[[main]]
weight = 3
name = "Blog"
hasChildren = true



[[main]]
parent = "Blog"
name = "Articles"
url = "blog/"



##  [[main]]
##  parent = "Pages"
##  name = "Blog"
##  url = "blog/"



[[main]]
parent = "Blog"
name = "Authors"
url = "authors/"

[[main]]
parent = "Blog"
name = "Categories"
url = "categories/"

[[main]]
parent = "Blog"
name = "Tags"
url = "tags/"

[[main]]
weight = 4
name = "Contact"
url = "contact/"

##  [[main]]
##  parent = "Blog"
##  name = "404 Page"
##  url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
