#################### default parameters ################################
# favicon
favicon = "images/favicon.png"

# logo
logo = "images/logo.png"

logo_darkmode = "images/logo-darkmode.png"

# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "160px"
logo_height = "32px"

# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true


# logo text will only show when logo is missing.
logo_text = "Tips4Engineers"


# navbar fixed to top
navbar_fixed = false


# theme-mode
theme_switcher = true
theme_default = "system" # available options [light/dark/system]


# Main Sections
mainSections = ["blog"]


# contact form action
contact_form_action = "https://airform.io/bakkalimounir41@gmail.com" # contact form works with [https://airform.io/] or [https://formspree.io]




# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "GTM-KKSDJDH4" # example: G-XXXXXXXXXX
google_adsense = "ca-pub-1428842133567087"     # example: ca-pub-xxxxxxxxxxxxxxxx


# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""


# copyright
copyright = "Owned By [Mounir El Bakkali](https://www.linkedin.com/in/mounirbakkali/)"

# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "get in touch"
link = "contact"

# search
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true


# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Mounir El Bakkali", "Software","Engineer","tips","developer","java","coding","problem solving","software engineering","learn","professional","portfolio","blogs","freelance","freelancer","React developer","Angular developer","developer tips","developer experience","developer lifestyle","developer life","developer blog","developer portfolio","dev","dev portfolio","dev tips","front-end","backend","microservices","spring boot","postgresql","hibernate","frontend engineering","databases","sql","nosql","mongodb","mysql","oracle","sql server","database","database management","database design","database administration","database development","database administ","ci/cd best practices","docker", "kubernetes","devops","devops engineer","devops tools","devops culture","devops practices","devops pipeline","devops engineer","devops architecture","devops automation","devops best practices","devops basics","devops concepts","devops culture","devops deployment","devops eng","delevoper lifestyle","oop","ood","uml","design principles","design patterns","software design","software architecture","software development","software engineering","software design patterns","software design principles","software design and architecture","software design and development","software development","software development life cycle","software development process","software development methodologies","software development tools","agie","developer tools","developer to entrepreneur","build tools","react best practice","developer in morocco","testing","testing tools","testing automation","testing best practices","testing techniques","testing strategies","testing engineer","testing automation engineer","testing automation tools","testing automation framework","testing automation best practices","testing automation strategy","testing automation process","testing automation interview questions","testing automation using python","testing automation using selenium","testing automation using java","testing automation using c#","testing automation using robot framework","testing automation using cypress","testing automation using javascript","testing automation using postman","testing automation using appium","testing automation using jenkins","testing automation using katalon","testing automation using selenium webdriver","testing automation using selenium python","testing automation using selenium java","testing automation using selenium c#","testing automation using selenium robot framework","testing automation using selenium cypress","testing automation using selenium javascript","testing automation using selenium postman","testing automation using selenium appium","testing automation using selenium jenkins","testing automation using selenium katalon"]
description = "Tips4Engineers is a blog website made for engineers , where Mounir El Bakkali shares his knowledge and experience in the field of software engineering , web development and programming in general ."
author = "Mounir El Bakkali"
image = "images/og-image.png"


# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = true
expire_days = 60
content = "This website uses cookies to enhance your browsing experience. By continuing to utilize this site, you are consenting to the utilization of these cookies to improve your interaction with the content."
button = "I Accept Recommeded Cookies"

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]


# google map
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"



[crisp_chat]
enable = true
crisp_website_id = "212bd6fd-4ed5-4894-830d-7b92b312b2d2"
